In [1]:
import pandas as pd
import sqlite3

In [2]:
conn = sqlite3.connect('/Users/orestis/MyProjects/InvestorAPI/app/database/ibd.db')

In [3]:
query = "SELECT * FROM price_prediction_dataset ORDER BY DATE(fiscal_date_ending)"

stocks_df = pd.read_sql(query, conn)

In [4]:
stocks_df.drop(["avg_global_commodities_index_value", "avg_volume"], axis='columns', inplace=True)

In [5]:
stocks_df.columns

Index(['symbol', 'fiscal_date_ending', 'reported_currency', 'gross_profit',
       'total_revenue', 'cost_of_revenue', 'cost_of_goods_and_services_sold',
       'operating_income', 'selling_general_and_administrative',
       'research_and_development', 'operating_expenses',
       'investment_income_net', 'net_interest_income', 'interest_income',
       'interest_expense', 'non_interest_income', 'other_non_operating_income',
       'depreciation', 'depreciation_and_amortization', 'income_before_tax',
       'income_tax_expense', 'interest_and_debt_expense',
       'net_income_from_continuing_operations',
       'comprehensive_income_net_of_tax', 'ebit', 'ebitda', 'net_income',
       'total_assets', 'total_current_assets',
       'cash_and_cash_equivalents_at_carrying_value',
       'cash_and_short_term_investments', 'inventory',
       'current_net_receivables', 'total_non_current_assets',
       'property_plant_equipment', 'accumulated_depreciation_amortization_ppe',
       'intangible_assets', 'intangible_assets_excluding_goodwill', 'goodwill',
       'investments', 'long_term_investments', 'short_term_investments',
       'other_current_assets', 'other_non_current_assets', 'total_liabilities',
       'total_current_liabilities', 'current_accounts_payable',
       'deferred_revenue', 'current_debt', 'short_term_debt',
       'total_non_current_liabilities', 'capital_lease_obligations',
       'long_term_debt', 'current_long_term_debt', 'long_term_debt_noncurrent',
       'short_long_term_debt_total', 'other_current_liabilities',
       'other_non_current_liabilities', 'total_shareholder_equity',
       'treasury_stock', 'retained_earnings', 'common_stock',
       'common_stock_shares_outstanding', 'operating_cashflow',
       'payments_for_operating_activities',
       'proceeds_from_operating_activities', 'change_in_operating_liabilities',
       'change_in_operating_assets', 'depreciation_depletion_and_amortization',
       'capital_expenditures', 'change_in_receivables', 'change_in_inventory',
       'profit_loss', 'cashflow_from_investment', 'cashflow_from_financing',
       'proceeds_from_repayments_of_short_term_debt',
       'payments_for_repurchase_of_common_stock',
       'payments_for_repurchase_of_equity',
       'payments_for_repurchase_of_preferred_stock', 'dividend_payout',
       'dividend_payout_common_stock', 'dividend_payout_preferred_stock',
       'proceeds_from_issuance_of_common_stock',
       'proceeds_from_issuance_of_long_term_debt_and_capital_securities_net',
       'proceeds_from_issuance_of_preferred_stock',
       'proceeds_from_repurchase_of_equity',
       'proceeds_from_sale_of_treasury_stock',
       'change_in_cash_and_cash_equivalents', 'change_in_exchange_rate',
       'sector', 'avg_interest_rate', 'avg_treasury_yield',
       'avg_natural_gas_price', 'avg_unemployment_rate', 'inflation', 'price'],
      dtype='object')

In [6]:
stocks_df.tail()

,symbol,fiscal_date_ending,reported_currency,gross_profit,total_revenue,cost_of_revenue,cost_of_goods_and_services_sold,operating_income,selling_general_and_administrative,research_and_development,...,proceeds_from_sale_of_treasury_stock,change_in_cash_and_cash_equivalents,change_in_exchange_rate,sector,avg_interest_rate,avg_treasury_yield,avg_natural_gas_price,avg_unemployment_rate,inflation,price
58499,KMX,2023-08-31,USD,696765000.0,7.073836e+09,6.377071e+09,4.020000e+07,32954000.0,585694000.0,0.0,...,0.0,0.0,0.0,TRADE & SERVICES,5.33,4.38,2.64,3.8,4.64285,69.460
58500,SNX,2023-08-31,USD,971273000.0,1.396062e+10,1.298934e+10,1.298934e+10,240233000.0,659454000.0,0.0,...,0.0,0.0,0.0,TECHNOLOGY,5.33,4.38,2.64,3.8,4.64285,98.775
58501,WOR,2023-08-31,USD,197489000.0,1.193256e+09,9.957670e+08,9.957670e+08,77705000.0,112348000.0,0.0,...,0.0,0.0,0.0,MANUFACTURING,5.33,4.38,2.64,3.8,4.64285,61.515
58502,MKC,2023-08-31,USD,622800000.0,1.684700e+09,1.061900e+09,1.061900e+09,245000000.0,371700000.0,0.0,...,0.0,0.0,0.0,MANUFACTURING,5.33,4.38,2.64,3.8,4.64285,72.025
58503,ACCD,2023-08-31,USD,87310000.0,1.937280e+08,1.064180e+08,5.531700e+07,-35208000.0,40335000.0,0.0,...,0.0,0.0,0.0,TRADE & SERVICES,5.33,4.38,2.64,3.8,4.64285,10.165

In [7]:
stocks_df['sector'].value_counts()

MANUFACTURING                 9769
LIFE SCIENCES                 9584
FINANCE                       8665
TECHNOLOGY                    8606
TRADE & SERVICES              8524
ENERGY & TRANSPORTATION       7900
REAL ESTATE & CONSTRUCTION    5456
Name: sector, dtype: int64

In [8]:
stocks_df['sector'].isnull().values.any()

False

In [9]:
stocks_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 58504 entries, 0 to 58503
Data columns (total 96 columns):
 #   Column                                                               Non-Null Count  Dtype
---  ------                                                               --------------  -----
 0   symbol                                                               58504 non-null  object
 1   fiscal_date_ending                                                   58504 non-null  object
 2   reported_currency                                                    58504 non-null  object
 3   gross_profit                                                         58504 non-null  float64
 4   total_revenue                                                        58504 non-null  float64
 5   cost_of_revenue                                                      58504 non-null  float64
 6   cost_of_goods_and_services_sold                                      58504 non-null  float64
 7   operating_income                                                     58504 non-null  float64
 8   selling_general_and_administrative                                   58504 non-null  float64
 9   research_and_development                                             58504 non-null  float64
 10  operating_expenses                                                   58504 non-null  float64
 11  investment_income_net                                                58504 non-null  float64
 12  net_interest_income                                                  58504 non-null  float64
 13  interest_income                                                      58504 non-null  float64
 14  interest_expense                                                     58504 non-null  float64
 15  non_interest_income                                                  58504 non-null  float64
 16  other_non_operating_income                                           58504 non-null  float64
 17  depreciation                                                         58504 non-null  float64
 18  depreciation_and_amortization                                        58504 non-null  float64
 19  income_before_tax                                                    58504 non-null  float64
 20  income_tax_expense                                                   58504 non-null  float64
 21  interest_and_debt_expense                                            58504 non-null  float64
 22  net_income_from_continuing_operations                                58504 non-null  float64
 23  comprehensive_income_net_of_tax                                      58504 non-null  float64
 24  ebit                                                                 58504 non-null  float64
 25  ebitda                                                               58504 non-null  float64
 26  net_income                                                           58504 non-null  float64
 27  total_assets                                                         58504 non-null  float64
 28  total_current_assets                                                 58504 non-null  float64
 29  cash_and_cash_equivalents_at_carrying_value                          58504 non-null  float64
 30  cash_and_short_term_investments                                      58504 non-null  float64
 31  inventory                                                            58504 non-null  float64
 32  current_net_receivables                                              58504 non-null  float64
 33  total_non_current_assets                                             58504 non-null  float64
 34  property_plant_equipment                                             58504 non-null  float64
 35  accumulated_depreciation_amortization_ppe                            58504 non-null  float64
 36  intangible_assets                                                    58504 non-null  float64
 37  intangible_assets_excluding_goodwill                                 58504 non-null  float64
 38  goodwill                                                             58504 non-null  float64
 39  investments                                                          58504 non-null  float64
 40  long_term_investments                                                58504 non-null  float64
 41  short_term_investments                                               58504 non-null  float64
 42  other_current_assets                                                 58504 non-null  float64
 43  other_non_current_assets                                             58504 non-null  float64
 44  total_liabilities                                                    58504 non-null  float64
 45  total_current_liabilities                                            58504 non-null  float64
 46  current_accounts_payable                                             58504 non-null  float64
 47  deferred_revenue                                                     58504 non-null  float64
 48  current_debt                                                         58504 non-null  float64
 49  short_term_debt                                                      58504 non-null  float64
 50  total_non_current_liabilities                                        58504 non-null  float64
 51  capital_lease_obligations                                            58504 non-null  float64
 52  long_term_debt                                                       58504 non-null  float64
 53  current_long_term_debt                                               58504 non-null  float64
 54  long_term_debt_noncurrent                                            58504 non-null  float64
 55  short_long_term_debt_total                                           58504 non-null  float64
 56  other_current_liabilities                                            58504 non-null  float64
 57  other_non_current_liabilities                                        58504 non-null  float64
 58  total_shareholder_equity                                             58504 non-null  float64
 59  treasury_stock                                                       58504 non-null  float64
 60  retained_earnings                                                    58504 non-null  float64
 61  common_stock                                                         58504 non-null  float64
 62  common_stock_shares_outstanding                                      58504 non-null  float64
 63  operating_cashflow                                                   58504 non-null  float64
 64  payments_for_operating_activities                                    58504 non-null  float64
 65  proceeds_from_operating_activities                                   58504 non-null  float64
 66  change_in_operating_liabilities                                      58504 non-null  float64
 67  change_in_operating_assets                                           58504 non-null  float64
 68  depreciation_depletion_and_amortization                              58504 non-null  float64
 69  capital_expenditures                                                 58504 non-null  float64
 70  change_in_receivables                                                58504 non-null  float64
 71  change_in_inventory                                                  58504 non-null  float64
 72  profit_loss                                                          58504 non-null  float64
 73  cashflow_from_investment                                             58504 non-null  float64
 74  cashflow_from_financing                                              58504 non-null  float64
 75  proceeds_from_repayments_of_short_term_debt                          58504 non-null  float64
 76  payments_for_repurchase_of_common_stock                              58504 non-null  float64
 77  payments_for_repurchase_of_equity                                    58504 non-null  float64
 78  payments_for_repurchase_of_preferred_stock                           58504 non-null  float64
 79  dividend_payout                                                      58504 non-null  float64
 80  dividend_payout_common_stock                                         58504 non-null  float64
 81  dividend_payout_preferred_stock                                      58504 non-null  float64
 82  proceeds_from_issuance_of_common_stock                               58504 non-null  float64
 83  proceeds_from_issuance_of_long_term_debt_and_capital_securities_net  58504 non-null  float64
 84  proceeds_from_issuance_of_preferred_stock                            58504 non-null  float64
 85  proceeds_from_repurchase_of_equity                                   58504 non-null  float64
 86  proceeds_from_sale_of_treasury_stock                                 58504 non-null  float64
 87  change_in_cash_and_cash_equivalents                                  58504 non-null  float64
 88  change_in_exchange_rate                                              58504 non-null  float64
 89  sector                                                               58504 non-null  object
 90  avg_interest_rate                                                    58504 non-null  float64
 91  avg_treasury_yield                                                   58504 non-null  float64
 92  avg_natural_gas_price                                                58504 non-null  float64
 93  avg_unemployment_rate                                                58504 non-null  float64
 94  inflation                                                            58504 non-null  float64
 95  price                                                                57105 non-null  float64
dtypes: float64(92), object(4)
memory usage: 42.8+ MB

In [10]:
stocks_df['price'].describe()

count    57105.000000
mean        67.289579
std        150.624749
min          0.107500
25%         15.430000
50%         33.755000
75%         71.875000
max       6341.885000
Name: price, dtype: float64

In [11]:
columns_with_null = stocks_df.columns[stocks_df.isna().any()].tolist()
columns_with_null

['price']

In [12]:
stocks_df.dropna(subset=columns_with_null, inplace=True)
stocks_df.reset_index(inplace=True)

In [13]:
stocks_df.tail()

,index,symbol,fiscal_date_ending,reported_currency,gross_profit,total_revenue,cost_of_revenue,cost_of_goods_and_services_sold,operating_income,selling_general_and_administrative,...,proceeds_from_sale_of_treasury_stock,change_in_cash_and_cash_equivalents,change_in_exchange_rate,sector,avg_interest_rate,avg_treasury_yield,avg_natural_gas_price,avg_unemployment_rate,inflation,price
57100,58499,KMX,2023-08-31,USD,696765000.0,7.073836e+09,6.377071e+09,4.020000e+07,32954000.0,585694000.0,...,0.0,0.0,0.0,TRADE & SERVICES,5.33,4.38,2.64,3.8,4.64285,69.460
57101,58500,SNX,2023-08-31,USD,971273000.0,1.396062e+10,1.298934e+10,1.298934e+10,240233000.0,659454000.0,...,0.0,0.0,0.0,TECHNOLOGY,5.33,4.38,2.64,3.8,4.64285,98.775
57102,58501,WOR,2023-08-31,USD,197489000.0,1.193256e+09,9.957670e+08,9.957670e+08,77705000.0,112348000.0,...,0.0,0.0,0.0,MANUFACTURING,5.33,4.38,2.64,3.8,4.64285,61.515
57103,58502,MKC,2023-08-31,USD,622800000.0,1.684700e+09,1.061900e+09,1.061900e+09,245000000.0,371700000.0,...,0.0,0.0,0.0,MANUFACTURING,5.33,4.38,2.64,3.8,4.64285,72.025
57104,58503,ACCD,2023-08-31,USD,87310000.0,1.937280e+08,1.064180e+08,5.531700e+07,-35208000.0,40335000.0,...,0.0,0.0,0.0,TRADE & SERVICES,5.33,4.38,2.64,3.8,4.64285,10.165

## Check for multicollinearity in the data

In [14]:
from statsmodels.stats.outliers_influence import variance_inflation_factor

def calc_vif(X):

    # Calculating VIF
    vif = pd.DataFrame()
    vif["variables"] = X.columns
    vif["VIF"] = [variance_inflation_factor(X.values, i) for i in range(X.shape[1])]

    return(vif)

In [15]:
stocks_df_only_numeric = stocks_df.drop(['symbol', 'fiscal_date_ending', 'reported_currency', 'sector', 'price'], axis=1)

In [16]:
stocks_df_only_numeric

,index,gross_profit,total_revenue,cost_of_revenue,cost_of_goods_and_services_sold,operating_income,selling_general_and_administrative,research_and_development,operating_expenses,investment_income_net,...,proceeds_from_issuance_of_preferred_stock,proceeds_from_repurchase_of_equity,proceeds_from_sale_of_treasury_stock,change_in_cash_and_cash_equivalents,change_in_exchange_rate,avg_interest_rate,avg_treasury_yield,avg_natural_gas_price,avg_unemployment_rate,inflation
0,2,2417031.0,5.689043e+06,3.272012e+06,3.272012e+06,1658477.0,795212.0,0.0,794643.0,0.0,...,0.0,0.0,0.0,-407116.0,324844.0,0.073333,2.046667,3.326667,8.633333,3.156842
1,4,1686513.0,5.284750e+06,3.598237e+06,3.598237e+06,-269682.0,1992276.0,0.0,2725727.0,0.0,...,0.0,0.0,0.0,1093579.0,257799.0,0.103333,2.036667,2.450000,8.266667,3.156842
2,6,1241275.0,3.315931e+06,2.074656e+06,2.074656e+06,454820.0,809392.0,0.0,1036063.0,0.0,...,0.0,0.0,0.0,-1395216.0,41252.0,0.153333,1.823333,2.280000,8.200000,2.069337
3,8,2740468.0,6.983128e+06,4.242660e+06,4.242660e+06,1928212.0,901732.0,0.0,832032.0,0.0,...,0.0,0.0,0.0,-1191328.0,-247599.0,0.143333,1.643333,2.880000,8.033333,2.069337
4,10,2067378.0,5.529120e+06,3.461742e+06,3.461742e+06,1411658.0,749865.0,0.0,888682.0,0.0,...,0.0,0.0,0.0,2057539.0,211511.0,0.160000,1.706667,3.400000,7.800000,2.069337
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
57100,58499,696765000.0,7.073836e+09,6.377071e+09,4.020000e+07,32954000.0,585694000.0,0.0,663811000.0,0.0,...,0.0,26333000.0,0.0,0.0,0.0,5.330000,4.380000,2.640000,3.800000,4.642850
57101,58500,971273000.0,1.396062e+10,1.298934e+10,1.298934e+10,240233000.0,659454000.0,0.0,731040000.0,0.0,...,0.0,0.0,0.0,0.0,0.0,5.330000,4.380000,2.640000,3.800000,4.642850
57102,58501,197489000.0,1.193256e+09,9.957670e+08,9.957670e+08,77705000.0,112348000.0,0.0,141515000.0,0.0,...,0.0,0.0,0.0,0.0,0.0,5.330000,4.380000,2.640000,3.800000,4.642850
57103,58502,622800000.0,1.684700e+09,1.061900e+09,1.061900e+09,245000000.0,371700000.0,0.0,371700000.0,0.0,...,0.0,-3300000.0,0.0,0.0,0.0,5.330000,4.380000,2.640000,3.800000,4.642850
57104,58503,87310000.0,1.937280e+08,1.064180e+08,5.531700e+07,-35208000.0,40335000.0,0.0,76755000.0,0.0,...,0.0,0.0,0.0,0.0,0.0,5.330000,4.380000,2.640000,3.800000,4.642850

In [17]:
vif_df = calc_vif(stocks_df_only_numeric)

In [18]:
vif_df

                          variables           VIF
0                             index  2.687266e-01
1                      gross_profit  2.256162e+01
2                     total_revenue  3.148712e+01
3                   cost_of_revenue  2.200098e+12
4   cost_of_goods_and_services_sold  2.200098e+12
..                              ...           ...
87                avg_interest_rate  1.271029e+00
88               avg_treasury_yield  1.069525e+00
89            avg_natural_gas_price  7.602598e-01
90            avg_unemployment_rate  3.921540e-01
91                        inflation  2.258508e+00

[92 rows x 2 columns]

In [29]:
vif_df.sort_values(by=['VIF'], ascending=False, inplace=True)

higher_than_10_list = []
less_or_equal_than_10_list = []
less_or_equal_than_5_list = []

for index, row in vif_df.iterrows():
    if row['VIF'] > 10:
        higher_than_10_list.append((row['variables'], row['VIF']))
    elif row['VIF'] <= 10 and row['VIF'] > 5:
        less_or_equal_than_10_list.append((row['variables'], row['VIF']))
    elif row['VIF'] <= 5:
        less_or_equal_than_5_list.append((row['variables'], row['VIF']))
    else:
        print("What the hell")

In [30]:
higher_than_10_list

[('cost_of_revenue', 2200097521920.125),
 ('cost_of_goods_and_services_sold', 2200097521920.125),
 ('cash_and_cash_equivalents_at_carrying_value', 282410461363.924),
 ('cash_and_short_term_investments', 282410461363.924),
 ('dividend_payout', 732264046.1787664),
 ('depreciation_depletion_and_amortization', 626055006.8759568),
 ('capital_expenditures', 152232564.54700467),
 ('inventory', 70406307.04256976),
 ('change_in_inventory', 70406305.39154112),
 ('dividend_payout_common_stock', 49544150.841671385),
 ('cashflow_from_financing', 37319634.511928156),
 ('cashflow_from_investment', 26032599.523547757),
 ('payments_for_operating_activities', 5772489.869958442),
 ('intangible_assets_excluding_goodwill', 917696.2121473273),
 ('intangible_assets', 917691.8270536492),
 ('income_before_tax', 101.78935145743615),
 ('total_assets', 90.20662372730821),
 ('ebitda', 76.22493174339255),
 ('net_income', 59.180290115855364),
 ('operating_income', 53.211721797554816),
 ('ebit', 51.02635158997049),
 ('total_shareholder_equity', 48.85420954529402),
 ('payments_for_repurchase_of_common_stock', 44.512874394180066),
 ('payments_for_repurchase_of_equity', 43.52521406134595),
 ('total_revenue', 31.487120636525727),
 ('total_liabilities', 30.41635028007461),
 ('short_long_term_debt_total', 22.585369097539555),
 ('gross_profit', 22.561616076439808),
 ('property_plant_equipment', 20.25642980017488),
 ('net_interest_income', 16.988076781708042),
 ('interest_income', 16.078698013018084),
 ('total_non_current_assets', 15.893973154534144),
 ('depreciation_and_amortization', 14.814660972119256),
 ('net_income_from_continuing_operations', 12.604314572450109),
 ('research_and_development', 10.367396193183978)]

In [27]:
len(less_or_equal_than_5_list)

52

## Handle columns with high VIF values

In [36]:
columns_to_keep = [
    'cash_and_short_term_investments',
    'dividend_payout',
    'total_assets',
    'net_income',
    'operating_income',
    'total_revenue',
    'total_liabilities',
]

higher_than_10_columns = [x[0] for x in higher_than_10_list]
columns_to_drop = list(set(higher_than_10_columns) - set(columns_to_keep))
columns_to_drop

['research_and_development',
 'payments_for_repurchase_of_equity',
 'gross_profit',
 'depreciation_and_amortization',
 'intangible_assets',
 'depreciation_depletion_and_amortization',
 'interest_income',
 'net_income_from_continuing_operations',
 'cash_and_cash_equivalents_at_carrying_value',
 'cost_of_revenue',
 'net_interest_income',
 'intangible_assets_excluding_goodwill',
 'cost_of_goods_and_services_sold',
 'ebit',
 'cashflow_from_investment',
 'inventory',
 'payments_for_operating_activities',
 'capital_expenditures',
 'total_non_current_assets',
 'ebitda',
 'total_shareholder_equity',
 'short_long_term_debt_total',
 'payments_for_repurchase_of_common_stock',
 'dividend_payout_common_stock',
 'property_plant_equipment',
 'change_in_inventory',
 'cashflow_from_financing',
 'income_before_tax']

In [37]:
stocks_df_only_numeric_reduced = stocks_df_only_numeric.drop(columns_to_drop, axis=1)

In [38]:
vif_df_v2 = calc_vif(stocks_df_only_numeric_reduced)

In [39]:
vif_df_v2.sort_values(by=['VIF'], ascending=False, inplace=True)

higher_than_10_list_v2 = []
less_or_equal_than_10_list_v2 = []
less_or_equal_than_5_list_v2 = []

for index, row in vif_df_v2.iterrows():
    if row['VIF'] > 10:
        higher_than_10_list_v2.append((row['variables'], row['VIF']))
    elif row['VIF'] <= 10 and row['VIF'] > 5:
        less_or_equal_than_10_list_v2.append((row['variables'], row['VIF']))
    elif row['VIF'] <= 5:
        less_or_equal_than_5_list_v2.append((row['variables'], row['VIF']))
    else:
        print("What the hell")

In [40]:
higher_than_10_list_v2

[('total_assets', 44.8246854679407),
 ('total_liabilities', 25.29382682050636),
 ('operating_income', 21.94660832099926),
 ('net_income', 11.550725743315972)]

In [42]:
stocks_df_only_numeric_reduced_v2 = stocks_df_only_numeric_reduced.drop(['operating_income', 'total_assets'], axis=1)
vif_df_v3 = calc_vif(stocks_df_only_numeric_reduced_v2)

higher_than_10_list_v3 = []
less_or_equal_than_10_list_v3 = []
less_or_equal_than_5_list_v3 = []

for index, row in vif_df_v3.iterrows():
    if row['VIF'] > 10:
        higher_than_10_list_v3.append((row['variables'], row['VIF']))
    elif row['VIF'] <= 10 and row['VIF'] > 5:
        less_or_equal_than_10_list_v3.append((row['variables'], row['VIF']))
    elif row['VIF'] <= 5:
        less_or_equal_than_5_list_v3.append((row['variables'], row['VIF']))
    else:
        print("What the hell")

In [44]:
less_or_equal_than_10_list_v3

[('total_revenue', 6.463455108970264),
 ('long_term_investments', 5.958797778352009),
 ('total_liabilities', 8.50549663132587)]

In [49]:
final_numeric_features = list(stocks_df_only_numeric_reduced_v2.columns)[1:] # Skip index column

In [50]:
final_numeric_features

['total_revenue',
 'selling_general_and_administrative',
 'operating_expenses',
 'investment_income_net',
 'interest_expense',
 'non_interest_income',
 'other_non_operating_income',
 'depreciation',
 'income_tax_expense',
 'interest_and_debt_expense',
 'comprehensive_income_net_of_tax',
 'net_income',
 'total_current_assets',
 'cash_and_short_term_investments',
 'current_net_receivables',
 'accumulated_depreciation_amortization_ppe',
 'goodwill',
 'investments',
 'long_term_investments',
 'short_term_investments',
 'other_current_assets',
 'other_non_current_assets',
 'total_liabilities',
 'total_current_liabilities',
 'current_accounts_payable',
 'deferred_revenue',
 'current_debt',
 'short_term_debt',
 'total_non_current_liabilities',
 'capital_lease_obligations',
 'long_term_debt',
 'current_long_term_debt',
 'long_term_debt_noncurrent',
 'other_current_liabilities',
 'other_non_current_liabilities',
 'treasury_stock',
 'retained_earnings',
 'common_stock',
 'common_stock_shares_outstanding',
 'operating_cashflow',
 'proceeds_from_operating_activities',
 'change_in_operating_liabilities',
 'change_in_operating_assets',
 'change_in_receivables',
 'profit_loss',
 'proceeds_from_repayments_of_short_term_debt',
 'payments_for_repurchase_of_preferred_stock',
 'dividend_payout',
 'dividend_payout_preferred_stock',
 'proceeds_from_issuance_of_common_stock',
 'proceeds_from_issuance_of_long_term_debt_and_capital_securities_net',
 'proceeds_from_issuance_of_preferred_stock',
 'proceeds_from_repurchase_of_equity',
 'proceeds_from_sale_of_treasury_stock',
 'change_in_cash_and_cash_equivalents',
 'change_in_exchange_rate',
 'avg_interest_rate',
 'avg_treasury_yield',
 'avg_natural_gas_price',
 'avg_unemployment_rate',
 'inflation']

In [16]:
final_features = [
    'total_revenue',
    'selling_general_and_administrative',
    'operating_expenses',
    'investment_income_net',
    'interest_expense',
    'non_interest_income',
    'other_non_operating_income',
    'depreciation',
    'income_tax_expense',
    'interest_and_debt_expense',
    'comprehensive_income_net_of_tax',
    'net_income',
    'total_current_assets',
    'cash_and_short_term_investments',
    'current_net_receivables',
    'accumulated_depreciation_amortization_ppe',
    'goodwill',
    'investments',
    'long_term_investments',
    'short_term_investments',
    'other_current_assets',
    'other_non_current_assets',
    'total_liabilities',
    'total_current_liabilities',
    'current_accounts_payable',
    'deferred_revenue',
    'current_debt',
    'short_term_debt',
    'total_non_current_liabilities',
    'capital_lease_obligations',
    'long_term_debt',
    'current_long_term_debt',
    'long_term_debt_noncurrent',
    'other_current_liabilities',
    'other_non_current_liabilities',
    'treasury_stock',
    'retained_earnings',
    'common_stock',
    'common_stock_shares_outstanding',
    'operating_cashflow',
    'proceeds_from_operating_activities',
    'change_in_operating_liabilities',
    'change_in_operating_assets',
    'change_in_receivables',
    'profit_loss',
    'proceeds_from_repayments_of_short_term_debt',
    'payments_for_repurchase_of_preferred_stock',
    'dividend_payout',
    'dividend_payout_preferred_stock',
    'proceeds_from_issuance_of_common_stock',
    'proceeds_from_issuance_of_long_term_debt_and_capital_securities_net',
    'proceeds_from_issuance_of_preferred_stock',
    'proceeds_from_repurchase_of_equity',
    'proceeds_from_sale_of_treasury_stock',
    'change_in_cash_and_cash_equivalents',
    'change_in_exchange_rate',
    'avg_interest_rate',
    'avg_treasury_yield',
    'avg_natural_gas_price',
    'avg_unemployment_rate',
    'inflation',
    'symbol', 
    'fiscal_date_ending',
    'sector',
    'price'
]

In [17]:
final_stocks_df = stocks_df[final_features]

In [20]:
final_stocks_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 57105 entries, 0 to 57104
Data columns (total 65 columns):
 #   Column                                                               Non-Null Count  Dtype
---  ------                                                               --------------  -----
 0   total_revenue                                                        57105 non-null  float64
 1   selling_general_and_administrative                                   57105 non-null  float64
 2   operating_expenses                                                   57105 non-null  float64
 3   investment_income_net                                                57105 non-null  float64
 4   interest_expense                                                     57105 non-null  float64
 5   non_interest_income                                                  57105 non-null  float64
 6   other_non_operating_income                                           57105 non-null  float64
 7   depreciation                                                         57105 non-null  float64
 8   income_tax_expense                                                   57105 non-null  float64
 9   interest_and_debt_expense                                            57105 non-null  float64
 10  comprehensive_income_net_of_tax                                      57105 non-null  float64
 11  net_income                                                           57105 non-null  float64
 12  total_current_assets                                                 57105 non-null  float64
 13  cash_and_short_term_investments                                      57105 non-null  float64
 14  current_net_receivables                                              57105 non-null  float64
 15  accumulated_depreciation_amortization_ppe                            57105 non-null  float64
 16  goodwill                                                             57105 non-null  float64
 17  investments                                                          57105 non-null  float64
 18  long_term_investments                                                57105 non-null  float64
 19  short_term_investments                                               57105 non-null  float64
 20  other_current_assets                                                 57105 non-null  float64
 21  other_non_current_assets                                             57105 non-null  float64
 22  total_liabilities                                                    57105 non-null  float64
 23  total_current_liabilities                                            57105 non-null  float64
 24  current_accounts_payable                                             57105 non-null  float64
 25  deferred_revenue                                                     57105 non-null  float64
 26  current_debt                                                         57105 non-null  float64
 27  short_term_debt                                                      57105 non-null  float64
 28  total_non_current_liabilities                                        57105 non-null  float64
 29  capital_lease_obligations                                            57105 non-null  float64
 30  long_term_debt                                                       57105 non-null  float64
 31  current_long_term_debt                                               57105 non-null  float64
 32  long_term_debt_noncurrent                                            57105 non-null  float64
 33  other_current_liabilities                                            57105 non-null  float64
 34  other_non_current_liabilities                                        57105 non-null  float64
 35  treasury_stock                                                       57105 non-null  float64
 36  retained_earnings                                                    57105 non-null  float64
 37  common_stock                                                         57105 non-null  float64
 38  common_stock_shares_outstanding                                      57105 non-null  float64
 39  operating_cashflow                                                   57105 non-null  float64
 40  proceeds_from_operating_activities                                   57105 non-null  float64
 41  change_in_operating_liabilities                                      57105 non-null  float64
 42  change_in_operating_assets                                           57105 non-null  float64
 43  change_in_receivables                                                57105 non-null  float64
 44  profit_loss                                                          57105 non-null  float64
 45  proceeds_from_repayments_of_short_term_debt                          57105 non-null  float64
 46  payments_for_repurchase_of_preferred_stock                           57105 non-null  float64
 47  dividend_payout                                                      57105 non-null  float64
 48  dividend_payout_preferred_stock                                      57105 non-null  float64
 49  proceeds_from_issuance_of_common_stock                               57105 non-null  float64
 50  proceeds_from_issuance_of_long_term_debt_and_capital_securities_net  57105 non-null  float64
 51  proceeds_from_issuance_of_preferred_stock                            57105 non-null  float64
 52  proceeds_from_repurchase_of_equity                                   57105 non-null  float64
 53  proceeds_from_sale_of_treasury_stock                                 57105 non-null  float64
 54  change_in_cash_and_cash_equivalents                                  57105 non-null  float64
 55  change_in_exchange_rate                                              57105 non-null  float64
 56  avg_interest_rate                                                    57105 non-null  float64
 57  avg_treasury_yield                                                   57105 non-null  float64
 58  avg_natural_gas_price                                                57105 non-null  float64
 59  avg_unemployment_rate                                                57105 non-null  float64
 60  inflation                                                            57105 non-null  float64
 61  symbol                                                               57105 non-null  object
 62  fiscal_date_ending                                                   57105 non-null  object
 63  sector                                                               57105 non-null  object
 64  price                                                                57105 non-null  float64
dtypes: float64(62), object(3)
memory usage: 28.3+ MB

In [32]:
final_stocks_df_only_numeric = final_stocks_df.drop(['symbol', 'fiscal_date_ending', 'sector'], axis=1)

In [33]:
final_stocks_df_only_numeric.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 57105 entries, 0 to 57104
Data columns (total 62 columns):
 #   Column                                                               Non-Null Count  Dtype
---  ------                                                               --------------  -----
 0   total_revenue                                                        57105 non-null  float64
 1   selling_general_and_administrative                                   57105 non-null  float64
 2   operating_expenses                                                   57105 non-null  float64
 3   investment_income_net                                                57105 non-null  float64
 4   interest_expense                                                     57105 non-null  float64
 5   non_interest_income                                                  57105 non-null  float64
 6   other_non_operating_income                                           57105 non-null  float64
 7   depreciation                                                         57105 non-null  float64
 8   income_tax_expense                                                   57105 non-null  float64
 9   interest_and_debt_expense                                            57105 non-null  float64
 10  comprehensive_income_net_of_tax                                      57105 non-null  float64
 11  net_income                                                           57105 non-null  float64
 12  total_current_assets                                                 57105 non-null  float64
 13  cash_and_short_term_investments                                      57105 non-null  float64
 14  current_net_receivables                                              57105 non-null  float64
 15  accumulated_depreciation_amortization_ppe                            57105 non-null  float64
 16  goodwill                                                             57105 non-null  float64
 17  investments                                                          57105 non-null  float64
 18  long_term_investments                                                57105 non-null  float64
 19  short_term_investments                                               57105 non-null  float64
 20  other_current_assets                                                 57105 non-null  float64
 21  other_non_current_assets                                             57105 non-null  float64
 22  total_liabilities                                                    57105 non-null  float64
 23  total_current_liabilities                                            57105 non-null  float64
 24  current_accounts_payable                                             57105 non-null  float64
 25  deferred_revenue                                                     57105 non-null  float64
 26  current_debt                                                         57105 non-null  float64
 27  short_term_debt                                                      57105 non-null  float64
 28  total_non_current_liabilities                                        57105 non-null  float64
 29  capital_lease_obligations                                            57105 non-null  float64
 30  long_term_debt                                                       57105 non-null  float64
 31  current_long_term_debt                                               57105 non-null  float64
 32  long_term_debt_noncurrent                                            57105 non-null  float64
 33  other_current_liabilities                                            57105 non-null  float64
 34  other_non_current_liabilities                                        57105 non-null  float64
 35  treasury_stock                                                       57105 non-null  float64
 36  retained_earnings                                                    57105 non-null  float64
 37  common_stock                                                         57105 non-null  float64
 38  common_stock_shares_outstanding                                      57105 non-null  float64
 39  operating_cashflow                                                   57105 non-null  float64
 40  proceeds_from_operating_activities                                   57105 non-null  float64
 41  change_in_operating_liabilities                                      57105 non-null  float64
 42  change_in_operating_assets                                           57105 non-null  float64
 43  change_in_receivables                                                57105 non-null  float64
 44  profit_loss                                                          57105 non-null  float64
 45  proceeds_from_repayments_of_short_term_debt                          57105 non-null  float64
 46  payments_for_repurchase_of_preferred_stock                           57105 non-null  float64
 47  dividend_payout                                                      57105 non-null  float64
 48  dividend_payout_preferred_stock                                      57105 non-null  float64
 49  proceeds_from_issuance_of_common_stock                               57105 non-null  float64
 50  proceeds_from_issuance_of_long_term_debt_and_capital_securities_net  57105 non-null  float64
 51  proceeds_from_issuance_of_preferred_stock                            57105 non-null  float64
 52  proceeds_from_repurchase_of_equity                                   57105 non-null  float64
 53  proceeds_from_sale_of_treasury_stock                                 57105 non-null  float64
 54  change_in_cash_and_cash_equivalents                                  57105 non-null  float64
 55  change_in_exchange_rate                                              57105 non-null  float64
 56  avg_interest_rate                                                    57105 non-null  float64
 57  avg_treasury_yield                                                   57105 non-null  float64
 58  avg_natural_gas_price                                                57105 non-null  float64
 59  avg_unemployment_rate                                                57105 non-null  float64
 60  inflation                                                            57105 non-null  float64
 61  price                                                                57105 non-null  float64
dtypes: float64(62)
memory usage: 27.0 MB

In [34]:
corr_matrix = final_stocks_df_only_numeric.corr()
corr_matrix["price"].sort_values(ascending=False)

price                              1.000000
comprehensive_income_net_of_tax    0.220717
profit_loss                        0.218051
current_accounts_payable           0.178442
current_net_receivables            0.172290
                                     ...
interest_expense                  -0.013906
total_liabilities                 -0.017625
total_current_assets              -0.017895
avg_treasury_yield                -0.018410
avg_interest_rate                 -0.025481
Name: price, Length: 62, dtype: float64

In [35]:
import numpy as np

# Find the strong correlations (> 0.7)
strong_correlations = np.where(np.abs(corr_matrix) > 0.7)

# Create a DataFrame to display the strong correlations
strong_correlations_df = pd.DataFrame({
    'Feature1': final_stocks_df_only_numeric.columns[strong_correlations[0]],
    'Feature2': final_stocks_df_only_numeric.columns[strong_correlations[1]],
    'Correlation': corr_matrix.values[strong_correlations]
})

# Filter out the correlations where Feature1 is not equal to Feature2
strong_correlations_df = strong_correlations_df[strong_correlations_df['Feature1'] != strong_correlations_df['Feature2']]

# Display the strong correlations
strong_correlations_df

,Feature1,Feature2,Correlation
11,comprehensive_income_net_of_tax,profit_loss,0.869262
14,total_current_assets,total_liabilities,0.724484
21,long_term_investments,short_term_investments,0.827935
22,long_term_investments,total_liabilities,0.862212
23,short_term_investments,long_term_investments,0.827935
25,short_term_investments,total_liabilities,0.765043
27,other_current_assets,total_liabilities,0.721592
29,total_liabilities,total_current_assets,0.724484
30,total_liabilities,long_term_investments,0.862212
31,total_liabilities,short_term_investments,0.765043
32,total_liabilities,other_current_assets,0.721592
35,total_current_liabilities,total_non_current_liabilities,0.792856
40,total_non_current_liabilities,total_current_liabilities,0.792856
57,profit_loss,comprehensive_income_net_of_tax,0.869262
71,avg_interest_rate,avg_treasury_yield,0.878326
72,avg_treasury_yield,avg_interest_rate,0.878326
75,avg_natural_gas_price,inflation,0.724403
77,inflation,avg_natural_gas_price,0.724403

In [36]:
strong_correlations_df['Feature1'].value_counts()

total_liabilities                  4
long_term_investments              2
short_term_investments             2
comprehensive_income_net_of_tax    1
total_current_assets               1
other_current_assets               1
total_current_liabilities          1
total_non_current_liabilities      1
profit_loss                        1
avg_interest_rate                  1
avg_treasury_yield                 1
avg_natural_gas_price              1
inflation                          1
Name: Feature1, dtype: int64

In [ ]:
# Drop total liabilities since we have total_current_liabilites and total_non_current_liabilities